services:
  # Servicio 1: La Web App (Django/Gunicorn)
  - type: web
    name: plataforma-web
    env: python
    plan: starter
    region: oregon
    pythonVersion: "3.12"
    buildFilter:
      paths:
      - "**.py"
      - "requirements.txt"
    # COMANDO CORREGIDO: Usa $(pwd) para tmp y fuerza CPU torch
    buildCommand: "mkdir -p tmp_build && export TMPDIR=$(pwd)/tmp_build && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install easyocr && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn plataforma.wsgi"
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plataforma-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: plataforma-redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

  # Servicio 2: El Worker Asíncrono (Celery)
  - type: worker
    name: plataforma-worker
    env: python
    plan: starter
    region: oregon
    pythonVersion: "3.12"
    buildFilter:
      paths:
      - "**.py"
      - "requirements.txt"
    # Aplicamos el mismo fix al worker para que tenga las librerías de IA disponibles
    buildCommand: "mkdir -p tmp_build && export TMPDIR=$(pwd)/tmp_build && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install easyocr && pip install -r requirements.txt"
    startCommand: "celery -A plataforma worker -l info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plataforma-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: plataforma-redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true

  # Servicio 3: El Broker de Tareas (Redis)
  - type: redis
    name: plataforma-redis
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Permitir todas las IPs (MVP)"

databases:
  - name: plataforma-db
    plan: free
    region: oregon
