# Especificación: 18.2 (Stack) y 19 (C4-4)
# Este archivo le dice a Render cómo construir nuestros 3 servicios.

services:
  # Servicio 1: La Web App (Django/Gunicorn)
  # (C4-4: Web Service, Plan Starter)
  - type: web
    name: plataforma-web
    env: python
    plan: starter # "Starter" para evitar que se suspenda (MVP Hosting)
    region: oregon
    buildFilter:
      paths:
      - "**.py"
      - "requirements.txt"
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn plataforma.wsgi"
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plataforma-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: plataforma-redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      # ---- ATENCIÓN: Añadir claves de R2 aquí en el Dashboard ----
      # CLOUDFLARE_R2_ACCOUNT_ID
      # CLOUDFLARE_R2_ACCESS_KEY_ID
      # CLOUDFLARE_R2_SECRET_ACCESS_KEY
      # CLOUDFLARE_R2_BUCKET_NAME

  # Servicio 2: El Worker Asíncrono (Celery)
  # (C4-4: Worker, Plan Starter)
  - type: worker
    name: plataforma-worker
    env: python
    plan: starter
    region: oregon
    buildFilter:
      paths:
      - "**.py"
      - "requirements.txt"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A plataforma worker -l info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plataforma-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: plataforma-redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true # Usar un valor distinto al de la web
      # ---- ATENCIÓN: Añadir claves de R2 aquí en el Dashboard ----

  # Servicio 3: El Broker de Tareas (Redis)
  # (C4-4: Broker de Tareas, Plan Free)
  - type: redis
    name: plataforma-redis
    plan: free
    region: oregon
    # --- !! CORRECCIÓN AÑADIDA AQUÍ !! ---
    ipAllowList:
      - ip: 0.0.0.0/0
        description: "Permitir todas las IPs (MVP)"

# Base de Datos (PostgreSQL)
# (C4-4: Base de Datos, Plan Free)
databases:
  - name: plataforma-db
    plan: free
    region: oregon
